import {
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Calculator,
  CalendarDays,
  ChartColumn,
  ClipboardList,
  FilePen,
  FileText,
  FolderOpen,
  Handshake,
  Landmark,
  LayoutGrid,
  Package,
  PiggyBank,
  Receipt,
  Scale,
  Search,
  ShieldCheck,
  Truck,
  UserCog,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

export const ICONES: Record<string, { icone: LucideIcon; label: string }> = {
  LayoutGrid: { icone: LayoutGrid, label: 'Geral' },
  Landmark: { icone: Landmark, label: 'Órgão público' },
  Building2: { icone: Building2, label: 'Empresa' },
  ClipboardList: { icone: ClipboardList, label: 'Processos' },
  FilePen: { icone: FilePen, label: 'Contrato' },
  FileText: { icone: FileText, label: 'Documento' },
  FolderOpen: { icone: FolderOpen, label: 'Pasta' },
  Calculator: { icone: Calculator, label: 'Cálculo' },
  ChartColumn: { icone: ChartColumn, label: 'Relatório' },
  Wallet: { icone: Wallet, label: 'Financeiro' },
  PiggyBank: { icone: PiggyBank, label: 'Banco' },
  Receipt: { icone: Receipt, label: 'Nota / guia' },
  Scale: { icone: Scale, label: 'Legislação' },
  CalendarDays: { icone: CalendarDays, label: 'Agenda' },
  Package: { icone: Package, label: 'Produto' },
  Boxes: { icone: Boxes, label: 'Estoque' },
  Truck: { icone: Truck, label: 'Transporte' },
  Users: { icone: Users, label: 'Pessoas' },
  UserCog: { icone: UserCog, label: 'Folha' },
  Briefcase: { icone: Briefcase, label: 'Administrativo' },
  Handshake: { icone: Handshake, label: 'Parceria' },
  BookOpen: { icone: BookOpen, label: 'Manual' },
  ShieldCheck: { icone: ShieldCheck, label: 'Certidão' },
  Search: { icone: Search, label: 'Consulta' },
  Wrench: { icone: Wrench, label: 'Ferramenta' },
}

export const iconeDe = (nome: string) => (ICONES[nome] ?? ICONES.LayoutGrid).icone

export const CORES: Record<string, { label: string; fundo: string; texto: string; forte: string }> = {
  brand: { label: 'Azul', fundo: 'bg-brand-100', texto: 'text-brand-600', forte: 'bg-brand-500' },
  emerald: { label: 'Verde', fundo: 'bg-emerald-100', texto: 'text-emerald-600', forte: 'bg-emerald-500' },
  amber: { label: 'Amarelo', fundo: 'bg-amber-100', texto: 'text-amber-600', forte: 'bg-amber-500' },
  violet: { label: 'Roxo', fundo: 'bg-violet-100', texto: 'text-violet-600', forte: 'bg-violet-500' },
  sky: { label: 'Azul-claro', fundo: 'bg-sky-100', texto: 'text-sky-600', forte: 'bg-sky-500' },
  rose: { label: 'Vermelho', fundo: 'bg-rose-100', texto: 'text-rose-600', forte: 'bg-rose-500' },
}

export const corDe = (nome: string) => CORES[nome] ?? CORES.brand
